#!/usr/bin/env node
/**
 * build-sidebar.mjs — 扫描 <category>/notes/ 目录自动生成 VitePress sidebar
 *
 * 扫描规则：
 *   - 扫描仓库根下每个 X/notes/ 目录，X 就是分类
 *   - X/notes/*.md        → 顶级项
 *   - X/notes/<sub>/*.md  → 子分组（sub 是子目录名）
 *
 * 显示标题：优先从 markdown 的 H1 提取，否则用 slug
 *
 * 用法：
 *   node scripts/build-sidebar.mjs
 *   输出：docs/.vitepress/sidebar.generated.mjs
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const REPO_ROOT = process.cwd();
const OUT_PATH = path.join(REPO_ROOT, "docs", ".vitepress", "sidebar.generated.mjs");

// 分类显示名映射（找不到就 fallback 到分类名）
const CATEGORY_TITLES = {
  AI: "AI",
  codex: "Codex 工具链",
  docker: "Docker 容器化",
  golang: "Go 后端学习路线",
  python: "Python",
  solidity: "Solidity",
  tools: "工具与排查",
};

// 子分组显示名映射（找不到就 fallback 到子目录名）
const SUBGROUP_TITLES = {
  "go-clean-arch": "go-clean-arch 项目拆解",
};

// 排除项：这些目录即使有 notes/ 也不当分类
const EXCLUDED_DIRS = new Set([
  "node_modules",
  ".git",
  ".github",
  "docs",
  "scripts",
  "dist",
  "build",
  ".vitepress",
  "out",
]);

function walkMd(dir, relBase = "") {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    if (entry.name === "README.md" || entry.name === "index.md") continue;
    const full = path.join(dir, entry.name);
    const rel = relBase ? `${relBase}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      out.push(...walkMd(full, rel));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      out.push(rel);
    }
  }
  return out;
}

function extractH1(filepath) {
  try {
    const content = fs.readFileSync(filepath, "utf-8");
    for (const line of content.split("\n")) {
      const m = line.match(/^#\s+(.+)$/);
      if (m) return m[1].trim();
    }
  } catch {}
  return null;
}

function buildCategorySidebar(category) {
  const notesDir = path.join(REPO_ROOT, category, "notes");
  if (!fs.existsSync(notesDir) || !fs.statSync(notesDir).isDirectory()) return null;

  const allFiles = walkMd(notesDir);
  if (allFiles.length === 0) return null;

  const topLevel = [];
  const subgroups = new Map();

  for (const rel of allFiles) {
    if (rel.includes("/")) {
      const slashIdx = rel.indexOf("/");
      const sub = rel.slice(0, slashIdx);
      const fname = rel.slice(slashIdx + 1);
      if (!subgroups.has(sub)) subgroups.set(sub, []);
      subgroups.get(sub).push(fname);
    } else {
      topLevel.push(rel);
    }
  }

  topLevel.sort();
  for (const arr of subgroups.values()) arr.sort();

  const items = [];

  for (const file of topLevel) {
    const slug = file.replace(/\.md$/, "");
    const title = extractH1(path.join(notesDir, file)) || slug;
    items.push({ text: title, link: `/${category}/${slug}` });
  }

  // 子分组按字母序
  const sortedSubs = [...subgroups.keys()].sort();
  for (const sub of sortedSubs) {
    const files = subgroups.get(sub);
    const subItems = files.map((file) => {
      const slug = file.replace(/\.md$/, "");
      const title = extractH1(path.join(notesDir, sub, file)) || slug;
      return { text: title, link: `/${category}/${sub}/${slug}` };
    });
    items.push({
      text: SUBGROUP_TITLES[sub] || sub,
      collapsed: false,
      items: subItems,
    });
  }

  return {
    text: CATEGORY_TITLES[category] || category,
    collapsed: false,
    items,
  };
}

// 扫仓库根
const sidebar = {};
const entries = fs.readdirSync(REPO_ROOT, { withFileTypes: true });
const categories = [];

for (const entry of entries) {
  if (!entry.isDirectory()) continue;
  if (entry.name.startsWith(".")) continue;
  if (EXCLUDED_DIRS.has(entry.name)) continue;
  const notesDir = path.join(entry.name, "notes");
  if (fs.existsSync(notesDir) && fs.statSync(notesDir).isDirectory()) {
    categories.push(entry.name);
  }
}

categories.sort();

for (const cat of categories) {
  const catSidebar = buildCategorySidebar(cat);
  if (catSidebar) sidebar[`/${cat}/`] = [catSidebar];
}

const banner = `// AUTO-GENERATED by scripts/build-sidebar.mjs — DO NOT EDIT
// 手写 sidebar 改 docs/.vitepress/config.mjs 里的 themeConfig.sidebar
`;

const out = banner + "export const generatedSidebar = " + JSON.stringify(sidebar, null, 2) + ";\n";

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, out, "utf-8");

// === 同步拷贝 notes 到 docs/（覆盖 symlink 让 VitePress build 不乱）===
const DOCS_DIR = path.join(REPO_ROOT, "docs");
const cpResult = [];
for (const cat of categories) {
  const src = path.join(REPO_ROOT, cat, "notes");
  const dst = path.join(DOCS_DIR, cat);
  // 删 dst（可能是 symlink 或旧目录），再拷过去
  fs.rmSync(dst, { recursive: true, force: true });
  // copySync 不支持递归拷目录，自己实现
  copyRecursiveSync(src, dst);
  cpResult.push(cat);
}

const topCount = Object.values(sidebar).flat().reduce((n, c) => n + c.items.filter((i) => !i.items).length, 0);
const subCount = Object.values(sidebar).flat().reduce((n, c) => n + c.items.filter((i) => i.items).reduce((m, g) => m + g.items.length, 0), 0);

console.log(`✓ 生成 ${path.relative(REPO_ROOT, OUT_PATH)}`);
console.log(`✓ 拷贝到 docs/: ${cpResult.join(", ") || "(无)"}`);
console.log(`  顶级笔记: ${topCount} 篇`);
console.log(`  子分组笔记: ${subCount} 篇`);

function copyRecursiveSync(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      copyRecursiveSync(s, d);
    } else {
      fs.copyFileSync(s, d);
    }
  }
}
